import * as PIXI from 'pixi.js';

/**
 * Sprite keys that correspond to filenames under /sprites/<key>.png.
 * These are generated by scripts/generate-sprites.mjs using the PixelLab API.
 */
export const SPRITE_KEYS = [
  // Subatomic tier
  'quark',
  'neutrino',
  'photon',
  'proton',
  // Atomic tier
  'electron',
  'ion',
  'nobleGas',
  'radioactiveIsotope',
  // Molecular tier
  'aminoAcid',
  'lipid',
  'freeRadical',
  // Player sprites (one per tier)
  'player_subatomic',
  'player_atomic',
  'player_molecular',
] as const;

export type SpriteKey = typeof SPRITE_KEYS[number];

/** Cache: null means texture failed to load (use fallback graphics) */
const textureCache = new Map<string, PIXI.Texture | null>();

/**
 * Attempt to preload all known sprite textures.
 * Missing files are silently ignored so the game always falls back to
 * procedural vector graphics when sprites haven't been generated yet.
 */
export async function preloadSprites(): Promise<void> {
  const loads = SPRITE_KEYS.map(async (key) => {
    try {
      const texture = await PIXI.Assets.load(`/sprites/${key}.png`);
      textureCache.set(key, texture);
    } catch {
      // Sprite not generated yet — use vector graphics fallback
      textureCache.set(key, null);
    }
  });
  await Promise.all(loads);
}

/**
 * Return the cached texture for a sprite key, or null if unavailable.
 * Only returns a valid texture after preloadSprites() has been called.
 */
export function getSprite(key: string): PIXI.Texture | null {
  return textureCache.get(key) ?? null;
}
